### ISSUE TITLE
`MenuLayer` открывает меню, позволяя подробнее управлять городом, общаться с сеньором и принимать важные решения.

### ISSUE THREAD

**Issue by korochun** [NamorNiradnug/Medieval-Rise#1]
- [ ] Придумать меню
- [ ] Написать слой

**Comment by NamorNiradnug** [comment]
Public methods of MenuLayer:
- [ ] MenuLayer.__init__()
- [ ] MenuLayer.setMenuType(menu_type)
- [ ] MenuLayer.paint(painter)
+ methods of Layer.

**Comment by NamorNiradnug** [comment]
Button - класс красивой кнопки. При наводке на нее она немного меняется. Соответственно, кнопка имеет параметры:
- [ ] click_function - то, что она делает при клике на нее
- [ ] ?action?_function - то, что она делает при наводке на нее (выскакивает меню справки, меняет внешний вид или т.п)
- [ ] layer, которому она добавляет свои listeners
- [ ] coords (на окне)
- [ ] image - ее внешний вид
